const defaultRetryDelaysMs = [1_000, 2_000] as const;

type FetchLike = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
type SleepLike = (delayMs: number, signal?: AbortSignal) => Promise<void>;

export class CustomerWindowHttpError extends Error {
  readonly retryable: boolean;
  readonly status: number;

  constructor(message: string, status: number, retryable = status >= 500 && status <= 599) {
    super(message);
    this.name = "CustomerWindowHttpError";
    this.retryable = retryable;
    this.status = status;
  }
}

export class CustomerWindowResponseError extends Error {
  constructor() {
    super("La respuesta del servidor no es válida.");
    this.name = "CustomerWindowResponseError";
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isAbortError(error: unknown) {
  return error instanceof Error && error.name === "AbortError";
}

function abortError() {
  return new DOMException("The operation was aborted.", "AbortError");
}

const defaultSleep: SleepLike = (delayMs, signal) => new Promise((resolve, reject) => {
  if (signal?.aborted) {
    reject(abortError());
    return;
  }

  const timer = window.setTimeout(() => {
    signal?.removeEventListener("abort", onAbort);
    resolve();
  }, delayMs);
  const onAbort = () => {
    window.clearTimeout(timer);
    reject(abortError());
  };
  signal?.addEventListener("abort", onAbort, { once: true });
});

export function isRetryableCustomerWindowReadError(error: unknown) {
  if (isAbortError(error) || error instanceof CustomerWindowResponseError) return false;
  if (error instanceof CustomerWindowHttpError) return error.retryable;
  return error instanceof TypeError;
}

export async function getCustomerWindowJson(
  url: string,
  signal?: AbortSignal,
  fetcher: FetchLike = fetch,
): Promise<Awaited<ReturnType<Response["json"]>>> {
  const response = await fetcher(url, { cache: "no-store", signal });
  let body: unknown = null;
  try {
    body = await response.json();
  } catch {
    // A 5xx response can be generated by infrastructure without a JSON body.
  }

  if (!response.ok) {
    const message = isRecord(body) && typeof body.error === "string"
      ? body.error
      : "No fue posible completar la consulta.";
    const retryable = isRecord(body) && typeof body.retryable === "boolean"
      ? body.retryable
      : response.status >= 500 && response.status <= 599;
    throw new CustomerWindowHttpError(message, response.status, retryable);
  }
  if (body === null) throw new CustomerWindowResponseError();
  return body;
}

export async function getCustomerWindowJsonWithRetry(
  url: string,
  signal?: AbortSignal,
  options: {
    fetcher?: FetchLike;
    retryDelaysMs?: readonly number[];
    sleep?: SleepLike;
  } = {},
) {
  const delays = options.retryDelaysMs ?? defaultRetryDelaysMs;
  const sleep = options.sleep ?? defaultSleep;

  for (let attempt = 0; ; attempt += 1) {
    try {
      return await getCustomerWindowJson(url, signal, options.fetcher);
    } catch (error) {
      if (!isRetryableCustomerWindowReadError(error) || attempt >= delays.length) throw error;
      await sleep(delays[attempt], signal);
    }
  }
}
