import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const read = (filePath) => fs.readFileSync(path.join(rootDir, filePath), "utf8");
const countMatches = (text, pattern) => [...text.matchAll(pattern)].length;

const migration = read("supabase/migrations/20260811180000_create_process_catalog_v2_views.sql");
const matrixFixMigration = read("supabase/migrations/20260811183000_fix_process_subprocess_matrix_v2.sql");
const data = read("src/lib/dashboard/data.ts");
const page = read("src/app/procesos/page.tsx");
const newProcessPage = read("src/app/procesos/nuevo/page.tsx");
const createProcessDraftForm = read("src/app/procesos/nuevo/create-process-draft-form.tsx");
const processClient = read("src/app/procesos/process-catalog-client.tsx");
const processUi = page + processClient;
const filters = read("src/components/dashboard/process-filters.tsx");
const adminActions = read("src/app/admin/actions.ts");
const detailModal = read("src/app/procesos/process-detail-modal.tsx");
const editModal = read("src/app/procesos/process-edit-modal.tsx");
const detailPage = read("src/app/procesos/[processId]/page.tsx");
const editPage = read("src/app/procesos/[processId]/editar/page.tsx");
const masterTypes = read("src/app/procesos/process-master/process-master-types.ts");
const masterMapper = read("src/app/procesos/process-master/process-master-mapper.ts");
const masterValidation = read("src/app/procesos/process-master/process-master-validation.ts");
const masterSheet = read("src/app/procesos/process-master/process-master-sheet.tsx");
const roleProfilesTable = read("src/app/procesos/process-master/process-role-profiles-table.tsx");
const stageEditor = read("src/app/procesos/[processId]/editar/stage-editor.tsx");

assert.match(migration, /create or replace view public\.v_process_catalog_v2/i, "must create V2 catalog view");
assert.match(migration, /create or replace view public\.v_process_subprocess_matrix_v2/i, "must create V2 stage view");
assert.match(matrixFixMigration, /create or replace view public\.v_process_subprocess_matrix_v2/i, "matrix fix must replace V2 stage view");
assert.doesNotMatch(matrixFixMigration, /\b(update|insert|delete|truncate)\b/i, "matrix fix migration must not mutate business data");
assert.match(matrixFixMigration, /with active_stage_base as/i, "matrix fix must define one base row per active stage");
assert.match(matrixFixMigration, /stage_owner as/i, "matrix fix must aggregate owner roles before joining");
assert.match(matrixFixMigration, /coalesce\(base\.subprocess_impact_percent, stage_owner\.owner_impact_percent\)::numeric\(5,2\) as impact_percent/, "impact_percent must preserve numeric(5,2) view contract");
assert.match(matrixFixMigration, /stage_user as/i, "matrix fix must aggregate user roles before joining");
assert.match(matrixFixMigration, /stage_support as/i, "matrix fix must aggregate support roles before joining");
assert.match(matrixFixMigration, /stage_backup as/i, "matrix fix must aggregate backup roles before joining");
assert.match(matrixFixMigration, /stage_systems as/i, "matrix fix must aggregate systems before joining");
assert.match(matrixFixMigration, /stage_risks_controls as/i, "matrix fix must aggregate risks and controls before joining");
assert.match(matrixFixMigration, /group by pr\.subprocess_id/g, "role aggregates must group by subprocess_id");
assert.match(matrixFixMigration, /from active_stage_base base[\s\S]*left join stage_owner[\s\S]*left join stage_user[\s\S]*left join stage_support[\s\S]*left join stage_backup[\s\S]*left join stage_systems[\s\S]*left join stage_risks_controls/i, "final matrix view must join aggregated CTEs to base stage rows");
assert.doesNotMatch(migration, /\b(update|insert|delete|truncate)\b/i, "V2 view migration must not mutate business data");
assert.match(migration, /p\.status = 'active'::public\.record_status/i, "catalog view must include active processes only");
assert.match(migration, /sp\.status = 'active'::public\.record_status/i, "stage view must include active stages only");
assert.match(migration, /responsibility_type in \([\s\S]*'consulted'::public\.responsibility_type[\s\S]*'executor'::public\.responsibility_type[\s\S]*'backup'::public\.responsibility_type[\s\S]*'user'::public\.responsibility_type/i, "support role summary must include support responsibility types");
assert.match(migration, /pr\.responsibility_type = 'owner'::public\.responsibility_type/i, "owner summary must use owner responsibilities");
assert.match(migration, /prsn\.status = 'active'::public\.record_status/i, "current people must use active person_roles");
assert.match(migration, /prsn\.end_date is null or prsn\.end_date >= current_date/i, "current people must respect vigente end_date");

assert.match(data, /export type ProcessCatalogV2Item/, "data helper must type V2 catalog rows");
assert.match(data, /export type ProcessStageV2Row/, "data helper must type V2 stage rows");
assert.match(data, /from\("v_process_catalog_v2"\)/, "data helper must query V2 catalog view");
assert.match(data, /from\("v_process_subprocess_matrix_v2"\)/, "data helper must query V2 stage view");
const processCatalogV2Type = data.slice(data.indexOf("export type ProcessCatalogV2Item"), data.indexOf("export type ProcessMatrixRow"));
assert.doesNotMatch(processCatalogV2Type, /:\s*any\b/, "V2 catalog type must not use any");

assert.match(processUi, /getProcessCatalogV2/, "process list must use V2 catalog helper");
assert.match(page, /href="\/procesos\/nuevo"/, "Nuevo proceso must navigate to the draft creation route");
assert.doesNotMatch(page, /CreateProcessModal/, "Nuevo proceso must not open the legacy modal from the list");
assert.match(newProcessPage, /<ProcessMasterSheet[\s\S]*mode="create"/, "draft creation route must render the shared master sheet in create mode");
assert.match(newProcessPage, /<CreateProcessDraftForm/, "draft creation route must keep the existing draft form inside the master sheet");
assert.match(createProcessDraftForm, /prepareDraftForWizard[\s\S]*autoCreateProcessDraft[\s\S]*router\.replace\(`\/procesos\/\$\{result\.processId\}\/editar\?wizard=create&step=2`/, "draft creation must autosave through the wizard before entering relational steps");
assert.match(newProcessPage, /eyebrow="Procesos"[\s\S]*title="Nuevo proceso"/, "page shell must keep one discreet Nuevo proceso heading");
assert.match(masterSheet, /if \(mode === "create"\)[\s\S]*actions \? <div[\s\S]*\{headerEditor\}/, "create mode must skip the duplicated readonly summary while retaining actions");
assert.equal(countMatches(createProcessDraftForm, /Ficha de proceso/gi), 1, "create UI must render one documentary sheet heading");
assert.doesNotMatch(createProcessDraftForm, /Nuevo proceso - borrador inicial|title="General"/, "create UI must remove redundant draft and General headings");
assert.match(createProcessDraftForm, /<Field label="Proceso">[\s\S]*name="name"[\s\S]*placeholder="Nombre del proceso"/, "Proceso must be the sole editable name field");
assert.doesNotMatch(createProcessDraftForm, /name="process_code"|name="version"/, "code and version must not be editable in create");
assert.doesNotMatch(createProcessDraftForm, /name="effective_date"|type="date"/, "document last-edited date must remain read-only in create");
assert.match(createProcessDraftForm, /autoCreateProcessDraft[\s\S]*name="name"/, "code must clearly remain automatic");
assert.match(createProcessDraftForm, /Field label="Dueno del proceso"[\s\S]*name="owner_role_id"[\s\S]*persona actual se deriva del rol/i, "owner must use the official role selector and person remains derived");
assert.match(createProcessDraftForm, /Ficha de proceso[\s\S]*Borrador/, "document version must use non-editable provisional copy");
assert.match(createProcessDraftForm, /Ficha de proceso[\s\S]*Borrador/, "create lifecycle state must remain Borrador");
assert.doesNotMatch(createProcessDraftForm, /Clasificaci&oacute;n y administraci&oacute;n|name="criticality"|name="documentation_status"/, "V1 create form must not duplicate technical classification fields");
assert.match(createProcessDraftForm, /className="grid gap-4 bg-\[#f8fafc\] px-5 py-4 sm:grid-cols-2"/, "documentary header must be responsive without a rigid table");
assert.doesNotMatch(createProcessDraftForm, /overflow-x-auto|whitespace-nowrap/, "create documentary header must not create horizontal overflow");
assert.match(processUi, /getProcessMatrixV2/, "process list must use V2 matrix helper");
assert.match(processUi, /Diccionario de procesos/, "dictionary heading must be clean");
assert.doesNotMatch(processUi, /Diccionario de procesos oficiales/, "dictionary heading must not use old wording");
assert.doesNotMatch(processUi, /Listado principal V2|Catalogo V2/, "visible process heading copy must not mention V2");
assert.doesNotMatch(processUi, /<AccordionPanel/, "main dictionary must not be globally collapsible");
assert.ok(["Tipo", "Proceso", "Rol due", "Persona actual", "Etapas", "Roles de apoyo", "Acci"].every((label) => processUi.includes(label)), "desktop columns must match V2 target");
assert.match(processUi, /const legacyProcessListGridColumns = "xl:grid-cols-\[88px_minmax\(260px,1fr\)_136px_126px_78px_144px_146px\]"[\s\S]*const newProcessListGridColumns = "xl:grid-cols-\[88px_minmax\(340px,1fr\)_148px_140px_78px_146px\]"/, "desktop grids must keep compact visible action columns at 1366px");
assert.doesNotMatch(processUi, /xl:grid-cols-\[120px_minmax\(300px,1fr\)_180px_180px_110px_220px_150px\]/, "desktop process grid must not use the clipped pre-action layout");
assert.match(processUi, /hidden gap-3[\s\S]*xl:grid \$\{gridColumns\}/, "desktop header must use the shared grid gap and column definition");
assert.match(processUi, /grid grid-cols-\[minmax\(0,1fr\)_auto\] gap-3 xl:items-center \$\{gridColumns\}/, "desktop rows must use the same shared grid definition as the header");
assert.match(processUi, /<span className="text-right">Acci/, "desktop action header must render as the final column");
assert.doesNotMatch(processUi, /<h3 className="text-base font-medium text-navy">[\s\S]*?process\.process_name[\s\S]*?<\/h3>[\s\S]*?<ValueBadge tone="neutral">\{process\.owner_company_name/, "process summary must not render company badges below the process name");
assert.doesNotMatch(processUi, /<h3 className="text-base font-medium text-navy">[\s\S]*?process\.process_name[\s\S]*?<\/h3>[\s\S]*?<TypedBadge type="criticality" value=\{process\.criticality\}/, "process summary must not render criticality badges below the process name");
assert.match(data, /owner_company_name: string \| null/, "company data must remain available for filters and details");
assert.match(data, /area_name: string \| null/, "area data must remain available for filters and details");
assert.match(data, /criticality: string/, "criticality data must remain available for filters and details");
assert.match(processUi, /process\.active_stage_count/, "process list must render active stage count");
assert.match(processUi, /current_person_names\.length === 0/, "process list must show persona fallback state");
assert.match(processUi, /function SupportRoleSummary/, "support roles must render through compact chip summary");
assert.match(processUi, /<ValueBadge tone="neutral">\{uniqueValues\[0\]\}<\/ValueBadge>[\s\S]*<ValueBadge tone="info">\+/, "support +N must be a separate chip");
assert.doesNotMatch(processUi, /overflow-x-auto/, "mobile list must not force horizontal table scrolling");
assert.ok(processUi.includes("aria-label={`Expandir o contraer"), "+/- process control must remain accessible");
assert.doesNotMatch(processUi, /import \{ ProcessEditModal \} from "\.\/process-edit-modal"/, "process list must not import the quick edit modal anymore");
assert.doesNotMatch(processUi, /href=\{`\/procesos\/\$\{process\.process_id\}\/editar`\}/, "catalog rows must not bypass the canonical process detail flow");
assert.match(processUi, /<ProcessDetailModal/, "Ver ficha action must remain available");
assert.doesNotMatch(processUi, /group-open\/process:hidden[\s\S]*group-open\/process:inline/, "desktop action column must not render the visual +/- control");
assert.match(processUi, /aria-label={`Expandir o contraer/, "native summary must keep the row expandable after removing +/-");
assert.match(detailModal, /event\.stopPropagation\(\)/, "Ver ficha modal must not toggle the summary");
assert.match(detailModal, /fetch\([\s\S]*api\/estructura\/procesos\/[\s\S]*process\.process_id[\s\S]*\/ficha/, "Ver ficha must load the authorized structure readonly endpoint");
assert.doesNotMatch(processUi, /<ProcessEditModal/, "process list must not open the quick edit modal");
assert.doesNotMatch(detailModal, /<ProcessEditModal/, "Ver ficha action must not open a parallel quick edit modal");
assert.doesNotMatch(detailModal, /\/editar/, "Ver ficha action must remain distinct from Editar");
assert.match(processUi, /generalQuery[\s\S]*matchesText\(process\.process_name, generalQuery\)[\s\S]*subprocess_name, generalQuery/, "general search must match process or active stage name");

for (const param of ["processType", "search", "ownerRole", "person", "supportRole", "company", "type"]) {
  assert.match(filters + processUi, new RegExp(param), `filter ${param} must exist`);
}

assert.match(filters, /Buscar proceso o etapa\.\.\./, "general search input must exist");
assert.match(filters, /SlidersHorizontal/, "filters button must use a clear control icon");
assert.match(filters, /aria-expanded=\{filtersOpen\}/, "filters button must expose expanded state");
assert.match(filters, /aria-controls=\{filtersPanelId\}/, "filters button must be associated to advanced panel");
assert.match(filters, /setFiltersOpen\(\(current\) => !current\)/, "filters button must toggle the panel");
assert.ok(filters.includes("advancedFilterCount > 0") && filters.includes("Filtros"), "filters button must show active advanced count");
assert.match(filters, /hasFilters \? \([\s\S]*Limpiar/, "clear button must be conditional");
assert.match(filters, /id=\{filtersPanelId\}/, "advanced filter panel must exist");
assert.match(filters, /ownerRole/, "owner role filter must be visible inside advanced panel");
assert.match(filters, /Roles de apoyo/, "support roles filter must be visible inside advanced panel");
assert.match(filters, /Persona/, "person filter must be visible inside advanced panel");
assert.doesNotMatch(filters, /useRouter|useSearchParams|router\.push|router\.replace/, "filters must not navigate on client-side changes");
assert.match(filters, /onFilterChange/, "filters must notify local state changes through callbacks");
assert.match(filters, /onClearFilters/, "clear filters must reset local state through a callback");
assert.match(processClient, /useState<ProcessFilterState>\(emptyFilters\)/, "process catalog client must keep filters in local state");
assert.match(processClient, /const filteredProcesses = useMemo/, "visible processes must be derived client-side from initial data");
assert.match(processClient, /setFilters\(emptyFilters\)/, "clear filters must restore the full in-memory catalog without navigation");
assert.doesNotMatch(filters, />\s*Proceso\s*<input/i, "process and stage must not remain as separate primary inputs");
assert.doesNotMatch(filters, />\s*Etapa\s*<input/i, "stage must not remain as a separate primary input");
assert.match(filters, /sm:grid-cols-2 \$\{newOnly \? "lg:grid-cols-3" : "xl:grid-cols-4"\}/, "advanced filters must use responsive mode-specific columns");

assert.match(detailModal, /ProcessMasterSheet mode="readonly"/, "Ver ficha must reuse the shared V1 readonly sheet");
assert.match(detailModal, /aria-label=\{`Ver ficha del proceso/, "Ver ficha link must remain accessible");
assert.doesNotMatch(detailModal, /Objetivo|Resultado esperado|Entradas y proveedores|Salidas y clientes|KPI basico|TypedBadge/, "quick action must not render a parallel legacy sheet");
assert.doesNotMatch(detailModal, /roleText|StageRoles|Objetivo|Resultado esperado/, "quick action must not duplicate the readonly read model");
assert.doesNotMatch(editModal, /ProcessMasterSheet/, "legacy quick edit component must not become a parallel master editor");
for (const field of ["purpose", "supplier_origin", "process_inputs", "process_outputs", "client_destination"]) {
  assert.match(editPage, new RegExp(`name="${field}"`), `advanced edit page must expose V1 field ${field}`);
}for (const field of ["process_start", "process_end", "scope"]) {
  assert.match(editPage + createProcessDraftForm, new RegExp(`name="${field}"`), `master create/edit UI must expose ${field}`);
}
for (const field of ["pdca_plan", "pdca_do", "pdca_check", "pdca_act"]) {
  assert.doesNotMatch(editPage + createProcessDraftForm, new RegExp(`name="${field}"`), `V1 UI must hide ${field}`);
}
assert.match(masterSheet, /process\.processCode/, "readonly master sheet must display process code from DTO");
assert.match(masterSheet, /documentaryDate\(process\.process\.masterUpdatedAt \?\? process\.process\.createdAt\)/, "readonly master sheet must display system last-edited date with created_at fallback");
assert.match(masterSheet, /process\.processStart[\s\S]*process\.processEnd[\s\S]*process\.scope/, "readonly master sheet must display start end and scope");
assert.doesNotMatch(masterSheet, /process\.process\.pdca\.plan|process\.process\.pdca\.act/, "V1 readonly sheet must hide PDCA fields while preserving DTO compatibility");
assert.doesNotMatch(createProcessDraftForm, /Ciclo de mejora opcional/, "create flow must hide PDCA in V1");
const updateBasics = adminActions.slice(adminActions.indexOf("async function persistProcessBasics"), adminActions.indexOf("export async function activateProcess"));
for (const field of ["purpose", "process_start", "process_end", "scope", "supplier_origin", "process_inputs", "process_outputs", "client_destination"]) {
  assert.match(updateBasics, new RegExp(`"${field}"`), `updateProcessBasics must support V1 field ${field}`);
}
assert.doesNotMatch(updateBasics, /inputs_providers|outputs_clients|basic_kpi|expected_result|pdca_(plan|do|check|act)/, "V1 edit actions must not overwrite hidden legacy fields");
assert.doesNotMatch(updateBasics, /process_code\s*:|version\s*:/, "ordinary edits must preserve process code and version");
assert.doesNotMatch(updateBasics, /effective_date|optionalDateValue/, "updateProcessBasics must not accept a manual effective date");
assert.match(updateBasics, /updates\.owner_role_id = ownerRoleId/, "updateProcessBasics must persist the validated direct process owner");
assert.match(masterSheet, /export function ProcessMasterSheet/, "shared process master sheet must exist");
assert.match(masterTypes, /export type ProcessMasterMode = "create" \| "edit" \| "readonly"/, "master sheet mode type must support create, edit and readonly");
assert.match(masterSheet, /1\. PROP\\u00d3SITO Y ALCANCE/, "master sheet must render purpose and scope section");
assert.match(masterSheet, /2\. ENTRADAS, ACTIVIDADES Y SALIDAS/, "master sheet must render inputs activities outputs section");
assert.match(masterSheet, /3\. ROLES, RESPONSABILIDADES Y AUTORIDAD/, "master sheet must render roles section");
assert.match(masterSheet, /4\. INDICADORES Y OBJETIVOS/, "master sheet must render indicators section");
assert.match(masterSheet, /5\. RIESGOS, CONTROLES Y OPORTUNIDADES/, "master sheet must render risks and controls section");
assert.doesNotMatch(masterSheet, /6\. Documentos y registros asociados/, "V1 master sheet must hide documents section");
assert.doesNotMatch(masterSheet, /7\. Ciclo de mejora/, "V1 master sheet must hide PDCA section");
assert.match(masterSheet, /No documentado/, "master sheet must show explicit empty states instead of invented values");
assert.match(masterSheet, /DocumentaryField label="Dueno del proceso"[\s\S]*DocumentaryField label="Codigo"[\s\S]*DocumentaryField label="Ultima edicion"/, "readonly header must keep the compact three-field documentary metadata");
assert.doesNotMatch(masterSheet, /DocumentaryField label="Version"/, "readonly header must hide version until formal versioning exists");
assert.match(masterSheet, /function StageList[\s\S]*stages\.map/, "master sheet must derive readonly activities from active stages");
assert.match(masterSheet, /flowEditor \? <div className="flex flex-col">\{flowEditor\}<ProcessDocumentRow[\s\S]*\{stageEditor\}[\s\S]*: <FlowTable/, "edit mode must show flow and stage editors while readonly uses the flow table");
assert.match(masterSheet, /RolesTable/, "master sheet must render roles independently from stages");
assert.match(roleProfilesTable, /Responsabilidad[\s\S]*Autoridad[\s\S]*Rendici\\u00f3n de cuentas/, "roles section must expose the V1 conceptual columns");
assert.doesNotMatch(masterSheet, /RiskControls/, "master sheet must not derive risks and controls from stages");
assert.match(masterSheet, /ProcessMasterDto/, "master sheet must use ProcessMasterDto as the single data source");
assert.match(detailPage, /<ProcessMasterSheet[\s\S]*mode="readonly"/, "readonly route must render the shared master sheet");
assert.match(editPage, /<ProcessMasterSheet[\s\S]*mode="edit"/, "edit route must render the shared master sheet");
assert.match(editPage, /stageEditor=\{[\s\S]*<StageEditor/, "edit route must keep StageEditor inside the master sheet");
assert.match(editPage, /headerEditor=\{headerEditor\}[\s\S]*purposeEditor=\{purposeEditor\}[\s\S]*flowEditor=\{flowEditor\}/, "edit route must place V1 documentary editors in the shared master sheet");
assert.match(masterMapper, /user_role_name: stage\.user_role_name/, "master DTO mapper must carry user role names");
assert.match(masterMapper, /support_role_names: stage\.support_role_name/, "master DTO mapper must carry support role names");
assert.match(masterMapper, /backup_role_name: stage\.backup_role_name/, "master DTO mapper must carry backup role names");
assert.match(masterMapper, /risks: stage\.risks[\s\S]*controls: stage\.controls/, "master DTO mapper must carry real risks and controls");
assert.match(masterTypes, /systems\?: string \| null[\s\S]*risks\?: string \| null[\s\S]*controls\?: string \| null/, "master DTO stage type must expose optional operational support fields");
assert.doesNotMatch(masterSheet, /Campos faltantes para ficha completa/, "technical missing-fields inventory must not render in the product UI");
assert.doesNotMatch(masterSheet, /Estado operativo|Estado documental|Criticidad/, "V1 sheet must hide duplicated technical status and criticality");
assert.match(masterSheet, /process\.process\.status === "active"[\s\S]*\? "Vigente"/, "active processes must use the user-facing Vigente label");
assert.doesNotMatch(stageEditor, /roles oficiales disponibles|RoleSelect/, "stage editor must not edit roles");
assert.doesNotMatch(stageEditor, /<section className="rounded-xl border border-line bg-white">[\s\S]*Diccionario de roles oficial/, "role dictionary must not render as a permanent full section");
assert.match(createProcessDraftForm, /autoCreateProcessDraft\(formData, "wizard_next"\)/, "create wizard must reuse the draft Server Action through its inline autosave contract");
assert.match(createProcessDraftForm, /router\.replace\(`\/procesos\/\$\{result\.processId\}\/editar\?wizard=create/, "create wizard must continue transparently in the persisted editor");
assert.doesNotMatch(masterSheet, /Math\.random|new Date\(\)/, "master sheet must not invent document metadata values");
assert.match(masterTypes, /export type ProcessMasterDto/, "process master DTO type must exist");
assert.match(masterMapper, /export function mapProcessMasterDto/, "process master mapper must exist");
assert.match(masterValidation, /export function validateProcessForActivation/, "process activation validator must exist");
assert.match(detailPage, /getProcessMasterReadModel\(processId\)/, "process detail page must use the canonical process master read model");
assert.match(detailPage, /getProcessMatrixV2/, "process detail page must use V2 stage helper");
assert.doesNotMatch(processUi + filters, /fetch\(/, "catalog controls must not introduce a client fetch mutation flow");
assert.equal((detailModal.match(/fetch\(/g) ?? []).length, 1, "Ver ficha may perform one authorized readonly fetch");
assert.match(processUi, /\/api\/procesos\/\$\{process\.process_id\}\/pdf/, "catalog must preserve the separately authorized PDF endpoint");

console.log("processes-v2-ui: 151/151 OK");
