import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const read = (filePath) => fs.readFileSync(path.join(rootDir, filePath), "utf8");

const migration = read("supabase/migrations/20260811180000_create_process_catalog_v2_views.sql");
const matrixFixMigration = read("supabase/migrations/20260811183000_fix_process_subprocess_matrix_v2.sql");
const data = read("src/lib/dashboard/data.ts");
const page = read("src/app/procesos/page.tsx");
const processClient = read("src/app/procesos/process-catalog-client.tsx");
const processUi = page + processClient;
const filters = read("src/components/dashboard/process-filters.tsx");
const adminActions = read("src/app/admin/actions.ts");
const detailModal = read("src/app/procesos/process-detail-modal.tsx");
const editModal = read("src/app/procesos/process-edit-modal.tsx");
const detailPage = read("src/app/procesos/[processId]/page.tsx");
const editPage = read("src/app/procesos/[processId]/editar/page.tsx");
const masterTypes = read("src/app/procesos/process-master/process-master-types.ts");
const masterMapper = read("src/app/procesos/process-master/process-master-mapper.ts");
const masterValidation = read("src/app/procesos/process-master/process-master-validation.ts");

assert.match(migration, /create or replace view public\.v_process_catalog_v2/i, "must create V2 catalog view");
assert.match(migration, /create or replace view public\.v_process_subprocess_matrix_v2/i, "must create V2 stage view");
assert.match(matrixFixMigration, /create or replace view public\.v_process_subprocess_matrix_v2/i, "matrix fix must replace V2 stage view");
assert.doesNotMatch(matrixFixMigration, /\b(update|insert|delete|truncate)\b/i, "matrix fix migration must not mutate business data");
assert.match(matrixFixMigration, /with active_stage_base as/i, "matrix fix must define one base row per active stage");
assert.match(matrixFixMigration, /stage_owner as/i, "matrix fix must aggregate owner roles before joining");
assert.match(matrixFixMigration, /coalesce\(base\.subprocess_impact_percent, stage_owner\.owner_impact_percent\)::numeric\(5,2\) as impact_percent/, "impact_percent must preserve numeric(5,2) view contract");
assert.match(matrixFixMigration, /stage_user as/i, "matrix fix must aggregate user roles before joining");
assert.match(matrixFixMigration, /stage_support as/i, "matrix fix must aggregate support roles before joining");
assert.match(matrixFixMigration, /stage_backup as/i, "matrix fix must aggregate backup roles before joining");
assert.match(matrixFixMigration, /stage_systems as/i, "matrix fix must aggregate systems before joining");
assert.match(matrixFixMigration, /stage_risks_controls as/i, "matrix fix must aggregate risks and controls before joining");
assert.match(matrixFixMigration, /group by pr\.subprocess_id/g, "role aggregates must group by subprocess_id");
assert.match(matrixFixMigration, /from active_stage_base base[\s\S]*left join stage_owner[\s\S]*left join stage_user[\s\S]*left join stage_support[\s\S]*left join stage_backup[\s\S]*left join stage_systems[\s\S]*left join stage_risks_controls/i, "final matrix view must join aggregated CTEs to base stage rows");
assert.doesNotMatch(migration, /\b(update|insert|delete|truncate)\b/i, "V2 view migration must not mutate business data");
assert.match(migration, /p\.status = 'active'::public\.record_status/i, "catalog view must include active processes only");
assert.match(migration, /sp\.status = 'active'::public\.record_status/i, "stage view must include active stages only");
assert.match(migration, /responsibility_type in \([\s\S]*'consulted'::public\.responsibility_type[\s\S]*'executor'::public\.responsibility_type[\s\S]*'backup'::public\.responsibility_type[\s\S]*'user'::public\.responsibility_type/i, "support role summary must include support responsibility types");
assert.match(migration, /pr\.responsibility_type = 'owner'::public\.responsibility_type/i, "owner summary must use owner responsibilities");
assert.match(migration, /prsn\.status = 'active'::public\.record_status/i, "current people must use active person_roles");
assert.match(migration, /prsn\.end_date is null or prsn\.end_date >= current_date/i, "current people must respect vigente end_date");

assert.match(data, /export type ProcessCatalogV2Item/, "data helper must type V2 catalog rows");
assert.match(data, /export type ProcessStageV2Row/, "data helper must type V2 stage rows");
assert.match(data, /from\("v_process_catalog_v2"\)/, "data helper must query V2 catalog view");
assert.match(data, /from\("v_process_subprocess_matrix_v2"\)/, "data helper must query V2 stage view");
const processCatalogV2Type = data.slice(data.indexOf("export type ProcessCatalogV2Item"), data.indexOf("export type ProcessMatrixRow"));
assert.doesNotMatch(processCatalogV2Type, /:\s*any\b/, "V2 catalog type must not use any");

assert.match(processUi, /getProcessCatalogV2/, "process list must use V2 catalog helper");
assert.match(processUi, /getProcessMatrixV2/, "process list must use V2 matrix helper");
assert.match(processUi, /Diccionario de procesos/, "dictionary heading must be clean");
assert.doesNotMatch(processUi, /Diccionario de procesos oficiales/, "dictionary heading must not use old wording");
assert.doesNotMatch(processUi, /Listado principal V2|Catalogo V2/, "visible process heading copy must not mention V2");
assert.doesNotMatch(processUi, /<AccordionPanel/, "main dictionary must not be globally collapsible");
assert.ok(["Tipo", "Proceso", "Rol due", "Persona actual", "Etapas", "Roles de apoyo", "Acci"].every((label) => processUi.includes(label)), "desktop columns must match V2 target");
assert.ok(processUi.includes('const processListGridColumns = "xl:grid-cols-[88px_minmax(260px,1fr)_144px_132px_86px_160px_154px]"'), "desktop process grid must keep a compact visible action column at 1366px");
assert.doesNotMatch(processUi, /xl:grid-cols-\[120px_minmax\(300px,1fr\)_180px_180px_110px_220px_150px\]/, "desktop process grid must not use the clipped pre-action layout");
assert.match(processUi, /hidden gap-3[\s\S]*xl:grid \$\{processListGridColumns\}/, "desktop header must use the shared grid gap and column definition");
assert.match(processUi, /grid grid-cols-\[minmax\(0,1fr\)_auto\] gap-3 xl:items-center \$\{processListGridColumns\}/, "desktop rows must use the same shared grid definition as the header");
assert.match(processUi, /<span className="text-right">Acci/, "desktop action header must render as the final column");
assert.doesNotMatch(processUi, /<h3 className="text-base font-medium text-navy">[\s\S]*?process\.process_name[\s\S]*?<\/h3>[\s\S]*?<ValueBadge tone="neutral">\{process\.owner_company_name/, "process summary must not render company badges below the process name");
assert.doesNotMatch(processUi, /<h3 className="text-base font-medium text-navy">[\s\S]*?process\.process_name[\s\S]*?<\/h3>[\s\S]*?<TypedBadge type="criticality" value=\{process\.criticality\}/, "process summary must not render criticality badges below the process name");
assert.match(data, /owner_company_name: string \| null/, "company data must remain available for filters and details");
assert.match(data, /area_name: string \| null/, "area data must remain available for filters and details");
assert.match(data, /criticality: string/, "criticality data must remain available for filters and details");
assert.match(processUi, /process\.active_stage_count/, "process list must render active stage count");
assert.match(processUi, /current_person_names\.length === 0/, "process list must show persona fallback state");
assert.match(processUi, /function SupportRoleSummary/, "support roles must render through compact chip summary");
assert.match(processUi, /<ValueBadge tone="neutral">\{uniqueValues\[0\]\}<\/ValueBadge>[\s\S]*<ValueBadge tone="info">\+/, "support +N must be a separate chip");
assert.doesNotMatch(processUi, /overflow-x-auto/, "mobile list must not force horizontal table scrolling");
assert.ok(processUi.includes("aria-label={`Expandir o contraer"), "+/- process control must remain accessible");
assert.match(processUi, /import \{ ProcessEditModal \} from "\.\/process-edit-modal"/, "process list must reuse existing edit modal");
assert.doesNotMatch(processUi, /triggerLabel="Editar"/, "process row edit action must not show visible Editar text");
assert.match(processUi, /triggerLabel=""/, "process row edit action must be icon-only");
assert.ok(processUi.includes("ariaLabel={`Editar proceso ${process.process_name}`}"), "edit action must include accessible label per process");
assert.match(processUi, /hidden h-9 w-9[\s\S]*xl:inline-flex/, "desktop edit action must be a compact icon-only control in the action column");
assert.match(processUi, /mb-4 flex flex-col gap-2 sm:flex-row xl:hidden[\s\S]*triggerLabel=""/, "mobile expanded panel must include icon-only Editar");
assert.match(processUi, /<ProcessDetailModal/, "Ver ficha action must remain available");
assert.doesNotMatch(processUi, /group-open\/process:hidden[\s\S]*group-open\/process:inline/, "desktop action column must not render the visual +/- control");
assert.match(processUi, /aria-label={`Expandir o contraer/, "native summary must keep the row expandable after removing +/-");
assert.match(detailModal, /event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*setOpen\(true\);/, "Ver ficha must not toggle the summary while opening the detail modal");
assert.match(editModal, /event\.preventDefault\(\);[\s\S]*event\.stopPropagation\(\);[\s\S]*setOpen\(true\);/, "Editar must not toggle the summary while opening the edit modal");
assert.match(editModal, /title="Editar proceso"/, "icon-only edit control must keep a tooltip title");
assert.match(processUi, /generalQuery[\s\S]*matchesText\(process\.process_name, generalQuery\)[\s\S]*subprocess_name, generalQuery/, "general search must match process or active stage name");

for (const param of ["processType", "search", "ownerRole", "person", "supportRole", "company", "type"]) {
  assert.match(filters + processUi, new RegExp(param), `filter ${param} must exist`);
}

assert.match(filters, /Buscar proceso o etapa\.\.\./, "general search input must exist");
assert.match(filters, /SlidersHorizontal/, "filters button must use a clear control icon");
assert.match(filters, /aria-expanded=\{filtersOpen\}/, "filters button must expose expanded state");
assert.match(filters, /aria-controls=\{filtersPanelId\}/, "filters button must be associated to advanced panel");
assert.match(filters, /setFiltersOpen\(\(current\) => !current\)/, "filters button must toggle the panel");
assert.ok(filters.includes("advancedFilterCount > 0") && filters.includes("Filtros"), "filters button must show active advanced count");
assert.match(filters, /hasFilters \? \([\s\S]*Limpiar/, "clear button must be conditional");
assert.match(filters, /id=\{filtersPanelId\}/, "advanced filter panel must exist");
assert.match(filters, /ownerRole/, "owner role filter must be visible inside advanced panel");
assert.match(filters, /Roles de apoyo/, "support roles filter must be visible inside advanced panel");
assert.match(filters, /Persona/, "person filter must be visible inside advanced panel");
assert.doesNotMatch(filters, /useRouter|useSearchParams|router\.push|router\.replace/, "filters must not navigate on client-side changes");
assert.match(filters, /onFilterChange/, "filters must notify local state changes through callbacks");
assert.match(filters, /onClearFilters/, "clear filters must reset local state through a callback");
assert.match(processClient, /useState<ProcessFilterState>\(emptyFilters\)/, "process catalog client must keep filters in local state");
assert.match(processClient, /const filteredProcesses = useMemo/, "visible processes must be derived client-side from initial data");
assert.match(processClient, /setFilters\(emptyFilters\)/, "clear filters must restore the full in-memory catalog without navigation");
assert.doesNotMatch(filters, />\s*Proceso\s*<input/i, "process and stage must not remain as separate primary inputs");
assert.doesNotMatch(filters, />\s*Etapa\s*<input/i, "stage must not remain as a separate primary input");
assert.match(filters, /sm:grid-cols-2 xl:grid-cols-4/, "advanced filters must wrap responsively");

assert.match(detailModal, /Entradas y proveedores/, "detail modal must show inputs/providers");
assert.match(detailModal, /Salidas y clientes/, "detail modal must show outputs/clients");
assert.match(detailModal, /KPI basico/, "detail modal must show basic KPI");
assert.match(detailModal, /Resultado esperado/, "detail modal must show expected result for documentary parity");
assert.match(detailModal, /Roles de apoyo/, "detail modal must show support roles");
assert.match(detailModal, /Etapas \/ subprocesos activos/, "detail modal must label active stages");
assert.doesNotMatch(detailModal, /Ficha V2 de proceso/, "detail modal must not show V2 to users");
assert.match(editModal, /name="inputs_providers"/, "quick edit modal must edit inputs/providers");
assert.match(editModal, /name="outputs_clients"/, "quick edit modal must edit outputs/clients");
assert.match(editModal, /name="basic_kpi"/, "quick edit modal must edit basic KPI");
assert.match(editPage, /name="inputs_providers"/, "advanced edit page must edit inputs/providers");
assert.match(editPage, /name="outputs_clients"/, "advanced edit page must edit outputs/clients");
assert.match(editPage, /name="basic_kpi"/, "advanced edit page must edit basic KPI");
assert.match(adminActions, /inputs_providers: optionalValue\(formData, "inputs_providers"\)/, "updateProcessBasics must persist inputs/providers");
assert.match(adminActions, /outputs_clients: optionalValue\(formData, "outputs_clients"\)/, "updateProcessBasics must persist outputs/clients");
assert.match(adminActions, /basic_kpi: optionalValue\(formData, "basic_kpi"\)/, "updateProcessBasics must persist basic KPI");
assert.doesNotMatch(adminActions, /owner_role_id:\s*optionalValue\(formData, "owner_role_id"\)/, "processes must not receive a direct owner_role_id model");
assert.match(masterTypes, /export type ProcessMasterDto/, "process master DTO type must exist");
assert.match(masterMapper, /export function mapProcessMasterDto/, "process master mapper must exist");
assert.match(masterValidation, /export function validateProcessForActivation/, "process activation validator must exist");
assert.match(detailPage, /getProcessCatalogV2Item/, "process detail page must use V2 catalog helper");
assert.match(detailPage, /getProcessMatrixV2/, "process detail page must use V2 stage helper");
assert.doesNotMatch(processUi + filters + detailModal, /api\/procesos|fetch\(/, "edit UI must not create a new endpoint or fetch flow");

console.log("processes-v2-ui: 79/79 OK");
